spring.application.name=transporte
spring.datasource.url=jdbc:h2:mem:transportedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Disable RabbitMQ active connection to allow tests without broker
spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.host=localhost
